main:
  build: .
  command: gin run
  #env_file: .env
  volumes:
    - ./:/go/src/github.com/gotstago/todoapp-go-es
  working_dir: /go/src/github.com/gotstago/todoapp-go-es
  ports:
    - "3000:3000"

typescript:
  image: gotstago/typescript
  #command: gin run
  #env_file: .env
  volumes:
    - ./app:/go/src/github.com/gotstago/todoapp-go-es/app
  working_dir: /go/src/github.com/gotstago/todoapp-go-es/app
 # ports:
 #   - "3000:3000"
# to run commands against running image
# docker exec -it <image name> <command>
# eg
# docker exec todoappgoes_main_1 golint ./...
# also see
# http://rancher.com/docker-based-build-pipelines-part-1-continuous-integration-and-testing/
