main:
  build: .
  command: gin run
  #env_file: .env
  volumes:
    - ./:/go/src/github.com/gotstago/todoapp-go-es
  working_dir: /go/src/github.com/gotstago/todoapp-go-es
  ports:
    - "3000:3000"
