FROM node:latest
RUN npm install -g typescript 
RUN npm install --global gulp
RUN npm install gulp
RUN npm install gulp-typescript 
ADD . /go/src/github.com/gotstago/todoapp-go-es/app
WORKDIR /go/src/github.com/gotstago/todoapp-go-es/app